apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret

type: Opaque

stringData:
  POSTGRES_DB: "<database-name>"
  POSTGRES_USER: "<database-user>"
  POSTGRES_PASSWORD: "<database-password>"